# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio16',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreinstitucion', models.CharField(blank=True, max_length=100, null=True)),
                ('codinst', models.CharField(blank=True, max_length=20, null=True)),
                ('nombremunicipio', models.CharField(blank=True, max_length=100, null=True)),
                ('codigomunicipio', models.IntegerField(blank=True, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('calendario', models.CharField(blank=True, max_length=2, null=True)),
                ('naturaleza', models.CharField(blank=True, max_length=30, null=True)),
                ('evaluados', models.IntegerField(blank=True, null=True)),
                ('prommatematica', models.FloatField(blank=True, null=True)),
                ('promsocialesyciudadanas', models.FloatField(blank=True, null=True)),
                ('promingles', models.FloatField(blank=True, null=True)),
                ('promcienciasnaturales', models.FloatField(blank=True, null=True)),
                ('promlecturacritica', models.FloatField(blank=True, null=True)),
                ('jornada', models.CharField(blank=True, max_length=50, null=True)),
                ('periodo', models.IntegerField(blank=True, null=True)),
                ('puntajeglobal', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'colegio16',
            },
        ),
    ]
