# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=130, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_dane', models.CharField(blank=True, max_length=30, null=True)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('clasificacion', models.CharField(blank=True, max_length=10, null=True)),
                ('evaluados', models.IntegerField(blank=True, null=True)),
                ('matriculados', models.IntegerField(blank=True, null=True)),
                ('ingles', models.FloatField(blank=True, null=True)),
                ('sociales', models.FloatField(blank=True, null=True)),
                ('matematicas', models.FloatField(blank=True, null=True)),
                ('ciencias', models.FloatField(blank=True, null=True)),
                ('lectura', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
