# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasification', '0002_auto_20171028_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
