# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saber2017', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colegio',
            old_name='prommatematicas',
            new_name='prommatematica',
        ),
    ]
